<a href="https://colab.research.google.com/github/dolynnyivlad-ai/go_it_dsml/blob/main/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size="10">Завдання</font>



In [2]:
import numpy as np


1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 2  7  2  5  1]
 [ 2  4  8  8  5]
 [ 1  4 10  4  8]
 [ 7  2  6  2 10]
 [10  3  7  4  6]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
a = np.random.random((4,4))
print(a)

[[0.76733039 0.03722979 0.98494685 0.01359931]
 [0.12114504 0.52812903 0.61299378 0.01273831]
 [0.26378648 0.45441112 0.60974404 0.56178787]
 [0.79006108 0.32592563 0.07145569 0.00237918]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(f'arr a: {a}, \n arr b: {b}')

add_ab = np.add(a, b)
print(f'add: {add_ab}')

subst_ab = np.subtract(a, b)
print(f'subtract: {subst_ab}')

mult_ab = np.multiply(a, b)
print(f'multiply: {mult_ab}')



arr a: [2 3 7 4 5], 
 arr b: [ 5 10  1  7 10]
add: [ 7 13  8 11 15]
subtract: [-3 -7  6 -3 -5]
multiply: [10 30  7 28 50]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(11, 21, size=7)
print(f'arr a: {a}, \n arr b: {b}')

result = np.dot(a, b)
print(f'scalar product: {result}')

arr a: [ 4  5 10  3  9  6  1], 
 arr b: [12 14 16 19 12 16 14]
scalar product: 553


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,3))
print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')

result = np.dot(a, b)
print(f'result:\n{result}')


arr a:
[[ 2  1]
 [10  1]]

arr b:
[[1 9 2]
 [9 5 3]]
result:
[[11 23  7]
 [19 95 23]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
a = np.random.randint(1, 11, size=(3,3))
print(f'arr a:\n{a}\n')

a_inv = np.linalg.inv(a)
print(f'inverse:\n{a_inv}')

arr a:
[[ 5  4  2]
 [10  8  5]
 [ 3  3  8]]

inverse:
[[-16.33333333   8.66666667  -1.33333333]
 [ 21.66666667 -11.33333333   1.66666667]
 [ -2.           1.          -0.        ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
a = np.random.random(size=(4,4))
print(f'arr a:\n{a}\n')

a_t = a.T
print(f'transposed:\n{a_t}')

arr a:
[[0.52426806 0.93788302 0.04654491 0.35202181]
 [0.19619837 0.46369121 0.41894573 0.49643694]
 [0.82114929 0.58815695 0.95391389 0.6839107 ]
 [0.70744276 0.26109573 0.85546114 0.10803169]]

transposed:
[[0.52426806 0.19619837 0.82114929 0.70744276]
 [0.93788302 0.46369121 0.58815695 0.26109573]
 [0.04654491 0.41894573 0.95391389 0.85546114]
 [0.35202181 0.49643694 0.6839107  0.10803169]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=4)
print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')

result = np.dot(a, b)
print(f'\n result:\n{result}')


arr a:
[[4 7 9 2]
 [3 6 2 4]
 [6 5 2 4]]

arr b:
[ 9  7 10  5]

 result:
[185 109 129]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
a = np.random.random((2,3))
b = np.random.random(3)
print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')

result = np.dot(a, b)
print(f'\n result:\n{result}')

arr a:
[[0.27915388 0.78623883 0.97422474]
 [0.85957441 0.17191403 0.82005218]]

arr b:
[0.40497825 0.78375325 0.5586895 ]

 result:
[1.27355762 0.94100166]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))

print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')


result = np.multiply(a, b)
print(f'\n result:\n{result}')


arr a:
[[6 4]
 [9 9]]

arr b:
[[10  3]
 [ 3  3]]

 result:
[[60 12]
 [27 27]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))

print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')


result = np.dot(a, b)
print(f'\n result:\n{result}')

arr a:
[[1 8]
 [4 4]]

arr b:
[[4 6]
 [3 9]]

 result:
[[28 78]
 [28 60]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.*Курсив*

In [ ]:
a = np.random.choice(np.arange(1, 101), size=(5,5), replace=False)
print(f'arr a:\n{a}\n')

result = np.sum(a)
print(f'\n result:\n{result}')

arr a:
[[40 48 73 17 36]
 [49 45 30 13 19]
 [44 27 59 12 61]
 [85 57 89 65 78]
 [80 21 29 81 26]]


 result:
1184


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
a = np.random.randint(1, 11, size=(4,4))
b = np.random.randint(1, 11, size=(4,4))
print(f'arr a:\n{a}\n')
print(f'arr b:\n{b}')

result = np.subtract(a, b)
print(f'\nresult:\n{result}')

arr a:
[[ 9  6  8  9]
 [10  4  3  9]
 [ 1  5 10  8]
 [ 5 10  1 10]]

arr b:
[[6 6 3 1]
 [4 5 8 7]
 [3 1 7 9]
 [4 7 1 4]]

result:
[[ 3  0  5  8]
 [ 6 -1 -5  2]
 [-2  4  3 -1]
 [ 1  3  0  6]]




```
# Выбран кодовый формат
```

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [10]:
a = np.round(np.random.random((3,3)), 2)
print(f'arr a:\n{a}\n')

result = np.sum(a, axis=1).reshape(-1,1)
print(f'result:\n{result}')

arr a:
[[0.11 0.16 0.97]
 [0.37 0.38 0.55]
 [0.95 0.17 0.69]]

result:
[[1.24]
 [1.3 ]
 [1.81]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [15]:
a = np.random.randint(1,10, size=(3,4))
print(f'arr a: \n{a}\n')

result = a ** 2
print(f'result:\n{result}')

arr a: 
[[3 4 3 7]
 [1 2 1 7]
 [9 8 6 6]]

result:
[[ 9 16  9 49]
 [ 1  4  1 49]
 [81 64 36 36]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
a = np.random.randint(1, 50, size=4)
print(f'arr: \n{a}\n')

result = np.sqrt(a)
print(f'result:\n{result}')

arr: 
[27 30  6 21]

result:
[5.19615242 5.47722558 2.44948974 4.58257569]


<font size="10">Завдання 2 (додаткове, за бажанням)</font>


1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6,
7, 8, 9])

In [23]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'original: {a}\n')

a[a % 2 != 0] = -1
print(f'replaced: {a}\n')

original: [0 1 2 3 4 5 6 7 8 9]

replaced: [ 0 -1  2 -1  4 -1  6 -1  8 -1]



2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [33]:
a = np.random.randint(1,10, size=8)
print(f'vector: {a}\n')

result = np.reshape(a, (2,4))
print(f'martix: \n{result}')

vector: [6 8 3 5 6 2 3 6]

martix: 
[[6 8 3 5]
 [6 2 3 6]]


3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [40]:
a = np.random.randint(1,10, size=(2,5))
b = np.random.randint(1,10, size=(2,5))
print(f'arr: \n{a}\n')
print(f'arr: \n{b}\n')


result = np.vstack((a,b))
print(f'stacked: \n{result}')


arr: 
[[1 8 8 7 9]
 [1 7 5 4 7]]

arr: 
[[9 8 7 4 6]
 [9 6 2 7 9]]

stacked: 
[[1 8 8 7 9]
 [1 7 5 4 7]
 [9 8 7 4 6]
 [9 6 2 7 9]]


4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [42]:
a = np.array([1,2,3])

part1 = np.repeat(a, 3)
part2 = np.tile(a, 3)

result = np.concatenate((part1, part2))

print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


5. Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.intersect1d(a,b)
print(result)

[2 4]


6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [48]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(f'{a}\n')

result = np.sort(a)[-5:]
print(result)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]

[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


7. Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])\

In [52]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

result = a[~np.isnan(a)]
print(result)
# [1. 2. 3. 5. 6. 7.]



[1. 2. 3. 5. 6. 7.]


8. Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [53]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

result = np.linalg.norm(a-b)

print(result)

6.708203932499369


8. Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [58]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

indices = np.where(x == 1)[0]
print(indices)

result = indices[4]
print(result)

[ 0  2  3  7  8 10 11]
8
